apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector-service
spec:
  template:
    spec:
      containers:
        - name: collector-service
          image: collector-service:latest
          imagePullPolicy: Never
          env:
            - name: DATABASE_URL
              value: "postgresql://foresee@postgres-cluster-rw:5432/foresee?sslmode=disable"
