apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector-service
spec:
  template:
    spec:
      containers:
        - name: collector-service
          env:
          - name: DATABASE_URL
            value: postgres://feedhub:feedhub-local-password@postgres-rw:5432/collector_db?sslmode=disable
