apiVersion: batch/v1
kind: Job
metadata:
  name: collector-migration
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: collector-migration:latest
          imagePullPolicy: Never
          env:
          - name: DATABASE_URL
            value: postgres://feedhub:feedhub-local-password@postgres-rw:5432/collector_db?sslmode=disable
