apiVersion: batch/v1
kind: Job
metadata:
  name: collector-migration
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: collector-migration:latest
          imagePullPolicy: Never
