apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foresee
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/boykush/foresee.git
    path: k8s/overlays/production/workloads
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
