[tools]
go = "1.25.5"
buf = "1.61.0"
kind = "0.26.0"
kubectl = "1.32.0"
pnpm = "10.29.3"
"go:github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway" = "v2.24.0"

[hooks]
postinstall = "env -u MISE_TOOL_VERSION mise run web:install"
