apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/platform

patches:
  - path: istio-ingressgateway/application-patch.yaml
    target:
      kind: Application
      name: istio-ingressgateway
  - path: feedhub/application-patch.yaml
    target:
      kind: Application
      name: feedhub
