apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- serviceaccount.yaml
- authorizationpolicy.yaml
images:
- name: web-service
  newName: ghcr.io/boykush/feedhub/web-service
  newTag: 8e3f77e
