apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: collector-authz
spec:
  selector:
    matchLabels:
      app: collector-service
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/default/sa/bff-service
        - cluster.local/ns/knative-serving/sa/controller
        - cluster.local/ns/istio-system/sa/istio-ingressgateway
