apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: collector-service
  labels:
    app: collector-service
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      labels:
        app: collector-service
      annotations:
        sidecar.istio.io/inject: "false"
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/max-scale: "1"
    spec:
      serviceAccountName: collector-service
      containers:
      - name: collector-service
        image: collector-service:latest
        ports:
        - containerPort: 50053
          name: h2c
          protocol: TCP
        env:
        - name: DATABASE_URL
          value: postgres://feedhub:feedhub-local-password@postgres-rw:5432/collector_db?sslmode=disable
        - name: COLLECTOR_SERVICE_PORT
          value: "50053"
