apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- serviceaccount.yaml
- authorizationpolicy.yaml
- migration-job.yaml
images:
- name: collector-migration
  newName: ghcr.io/boykush/feedhub/collector-migration
  newTag: 60dd333
- name: collector-service
  newName: ghcr.io/boykush/feedhub/collector-service
  newTag: 60dd333
