apiVersion: v1
kind: Service
metadata:
  name: collector-service
  labels:
    app: collector-service
spec:
  type: ClusterIP
  ports:
  - port: 50053
    targetPort: 50053
    protocol: TCP
    name: grpc
  selector:
    app: collector-service
