apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
spec:
  template:
    spec:
      containers:
        - name: transaction-service
          image: transaction-service:latest
          imagePullPolicy: Never
          env:
            - name: STORAGE_ENDPOINT
              value: "http://minio.default.svc.cluster.local:9000"
            - name: STORAGE_BUCKET
              value: "transactions"
            - name: STORAGE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: root-user
            - name: STORAGE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: root-password
