apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: bff-authz
spec:
  selector:
    matchLabels:
      app: bff-service
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/istio-system/sa/istio-ingressgateway
        - cluster.local/ns/default/sa/web-service
