apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- serviceaccount.yaml
- authorizationpolicy.yaml
images:
- name: bff-service
  newName: ghcr.io/boykush/feedhub/bff-service
  newTag: e468a3d
