apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- serviceaccount.yaml
- authorizationpolicy.yaml
- migration-job.yaml
images:
- name: feed-migration
  newName: ghcr.io/boykush/feedhub/feed-migration
  newTag: fc1e284
- name: feed-service
  newName: ghcr.io/boykush/feedhub/feed-service
  newTag: e468a3d
