name: Collector CI

on:
  pull_request:
    paths:
      - 'server/collector/**'
      - '.github/workflows/collector-ci.yml'
      - '.github/actions/go-ci/**'
  push:
    branches:
      - main
    paths:
      - 'server/collector/**'
      - '.github/workflows/collector-ci.yml'
      - '.github/actions/go-ci/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Go CI
        uses: ./.github/actions/go-ci
        with:
          service: collector
